AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for Fargate
Parameters:
  AppName:
    Type: String
    Default: surveyapp
  EnvName:
    Type: String
    Default: prod  
  VPC:
    Type: 'AWS::EC2::VPC::Id'
  AutoScalingTargetValue:
    Type: Number
    Default: 80
  MaxTasks:
    Type: Number
    Default: 1
  MinTasks:
    Type: Number
    Default: 1
  ContainerPort:
    Type: Number
    Default: 80
  SubnetB:
    Type: String
    Default: subnet-4e53e129
  SubnetC:
    Type: String
    Default: subnet-85bb02ab
  PathPattern:
    Type: String
    Default: /
  HealthCheckPath:
    Type: String
    Default: /
  ListenerRule1Priority:
    Type: Number
    Default: 1
  SGCidrIp:
    Type: String
    Default: 172.31.0.0/16
  InternalALB:
    Type: String
    Default: ''

Resources:  
  Service:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - ListenerRule1
    Properties:
      ServiceName: !Ref AppName
      Cluster: 
        'Fn::ImportValue': !Join 
          - ''
          - - !Ref EnvName
            - Cluster
      TaskDefinition:  !Join 
        - ''
        - - 'ads-'
          - !Ref EnvName
          - '-'
          - !Ref AppName
          - '-task'
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetB
            - !Ref SubnetC
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref AppName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
  AutoScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Join 
        - ''
        - - 'ads-'
          - !Ref EnvName
          - '-'
          - !Ref AppName
          - '-autoscale-policy'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 180
        ScaleOutCooldown: 180
        TargetValue: !Ref AutoScalingTargetValue
  AutoScalingTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MinCapacity: !Ref MinTasks
      MaxCapacity: !Ref MaxTasks
      ResourceId: !Join 
        - /
        - - service
          - 'Fn::ImportValue': !Join 
              - ''
              - - !Ref EnvName
                - Cluster
          - !GetAtt 
            - Service
            - Name
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
      RoleARN: 
        'Fn::ImportValue': !Join 
          - ''
          - - !Ref EnvName
            - AutoScalingRole
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckTimeoutSeconds: 10
      UnhealthyThresholdCount: 3
      HealthyThresholdCount: 3
      Name: !Join 
        - ''
        - - 'ads-'
          - !Ref EnvName
          - '-'
          - !Ref AppName
          - !Ref InternalALB          
          - '-tg'
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      VpcId: !Ref VPC            
  ContainerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Join 
        - ''
        - - 'ads-'
          - !Ref EnvName
          - '-'
          - !Ref AppName
          - '-container-sg'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: 
            'Fn::ImportValue': !Join 
              - ''
              - - !Ref EnvName
                - !Ref InternalALB
                - LoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: !Ref SGCidrIp

  ListenerRule1:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - !Ref PathPattern
      ListenerArn: 
        'Fn::ImportValue': !Join 
          - ''
          - - !Ref EnvName
            - !Ref InternalALB
            - ListenerHTTPS
      Priority: !Ref ListenerRule1Priority
